 {{- range $key, $value := .Values.Apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $value.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $value.name }}
  template:
    metadata:
      labels:
        app: {{ $value.name }}
    spec:
      containers:
      - name: {{ $value.name }}
        image: {{ $value.image }}
        ports:
        - containerPort: {{ $value.port }}
        
{{- end }}    
