{{- range $key, $value := .Values.Apps }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $value.name }}-service
spec:
  type: NodePort
  selector:
    app: {{ $value.name }}
  ports:
    - protocol: TCP
      port:  {{ $value.port }}
      targetPort:  {{ $value.port }}
      nodePort: {{ $value.nodePort }}
{{- end }}
